[tool.pdm.version]
source = "scm"
version_format = "pdm_build:format_version"

[project]
dynamic = ["version"]

name = "sphinxcontrib-yowasp-wavedrom"
description = "A Sphinx extension for embedding WaveDrom diagrams"
readme = "README.md"
authors = [{name = "Catherine", email = "whitequark@whitequark.org"}]
license = {text = "MIT"}
classifiers = [
	"License :: OSI Approved :: MIT License"
]

requires-python = "~=3.12.7"
dependencies = [
    "Sphinx~=8.1",
    "yowasp-wavedrom>=3.5.0.8",
    "json5~=0.9", # trailing commas
]

[build-system]
requires = ["pdm-backend~=2.3.0"]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = ["sphinxcontrib/"] # required for a namespace package

[tool.pdm.dev-dependencies]
test = ["furo"]

[tool.pdm.scripts]
test = "sphinx-build -aE -b html test test/_out"
